version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/c/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/d/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/e/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/f/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/g/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/article/h/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/babel/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/babel/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/babel/c/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/babel/d/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/babel/e/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/c/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/d/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/e/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/f/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/g/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/h/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/i/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/css/j/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/enhanced/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/enhanced/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/enhanced/c/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/enhanced/d/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/enhanced/e/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/minimal/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/minimal/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/minimal/c/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/minimal/d/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/minimal/e/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/minimal/f/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/named/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/named/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/c/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/d/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/e/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/f/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/g/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/h/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/timeline/i/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/uglify/a/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/uglify/b/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "playground/uglify/c/"
    update_schedule: "live"